apiVersion: v1
kind: Secret
metadata:
  name: fullstack-secrets
  namespace: fullstack
type: Opaque
data:
  # Base64 encoded values (Example: "secret" -> "c2VjcmV0")
  # echo -n "supersecretkey" | base64
  API_SECRET_KEY: c3VwZXJzZWNyZXRrZXk=
